# Generated by Django 2.2.1 on 2019-05-30 01:19

from django.db import migrations


class Migration(migrations.Migration):


    dependencies = [
        ('booktest', '0004_areainfo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='bookinfo',
        ),
    ]


    atomic = False