# Generated by Django 2.2.1 on 2019-06-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_auto_20190530_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroinfo',
            name='hcomment',
            field=models.CharField(max_length=128, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hgender',
            field=models.BooleanField(default=False, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='标记'),
        ),
    ]
