# Generated by Django 2.2.1 on 2019-06-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0009_auto_20190612_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpic', models.ImageField(upload_to='booktest')),
            ],
        ),
        migrations.AlterModelOptions(
            name='bookinfo',
            options={'ordering': ['id'], 'verbose_name': '图书列表', 'verbose_name_plural': '图书'},
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='btitle',
            field=models.CharField(max_length=20, verbose_name='书名'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hcomment',
            field=models.TextField(verbose_name='介绍'),
        ),
        migrations.AlterField(
            model_name='heroinfo',
            name='hname',
            field=models.CharField(max_length=20, unique=True, verbose_name='名称'),
        ),
    ]
